apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    jaegertracing.io/operated-by: openshift-operators.jaeger-operator
  name: amqs-jaeger
  namespace: amqs
spec:
  strategy: allinone
  ui:
    options:
      menu:
        - items:
            - label: Documentation
              url: >-
                https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/jaeger/index
          label: About
        - anchorTarget: _self
          label: Log Out
          url: /oauth/sign_in
  ingress:
    openshift: {}
    options: {}
    resources: {}
    security: oauth-proxy
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: '1'
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    options: {}
    type: memory
