apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
  namespace: amqs-target
spec:
  clusters:
    - alias: my-source-cluster
      authentication:
        passwordSecret:
          password: password
          secretName: mm2-credentials
        type: scram-sha-512
        username: my-user
      bootstrapServers: 'my-cluster-kafka-bootstrap.amqs-01.svc:9093'
    - alias: my-target-cluster
      bootstrapServers: 'my-cluster-target-kafka-bootstrap.amqs-01-target.svc:9092'
      config:
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  connectCluster: my-target-cluster
  livenessProbe:
    initialDelaySeconds: 25
    timeoutSeconds: 25
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
          replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
          replication.policy.separator: ''
      groupsPattern: .*
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      sourceCluster: my-source-cluster
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: 1
          replication.factor: 1
          replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
          replication.policy.separator: ''
          sync.topic.acls.enabled: 'true'
      targetCluster: my-target-cluster
      topicsPattern: .*
  readinessProbe:
    initialDelaySeconds: 25
    timeoutSeconds: 25
  replicas: 1
  version: 2.8.0
