kind: Secret
apiVersion: v1
metadata:
  name: mm2-credentials
  namespace: amqs-target
  labels:
    app.kubernetes.io/instance: mm2-credentials
    app.kubernetes.io/managed-by: strimzi-user-operator
    app.kubernetes.io/name: strimzi-user-operator
    app.kubernetes.io/part-of: strimzi-mm2-credentials
    strimzi.io/cluster: my-cluster-target
    strimzi.io/kind: KafkaUser
data:
  password: <base64 password>
type: Opaque
